### ISSUE TITLE
Feature request [IOS SUPPORT]

### ISSUE THREAD

**Issue by vlimag** [kevinejohn/react-native-keyevent#18]
Hi, 

Do you have any prediction for IOS Support release?

Thanks

**Comment by kevinejohn** [comment]
I currently don't have any plans to build it for iOS but I will gladly accept pull requests

**Comment by bhenav** [comment]
hi,

please support for ios :)

thank you.

**Comment by kevinejohn** [comment]
Someone made a PR. Can anyone test and verify it works?

https://github.com/kevinejohn/react-native-keyevent/pull/28

**Comment by kevinejohn** [comment]
The iOS PR was just merged
