### ISSUE TITLE
not getting backpressed keyCodes.

### ISSUE THREAD

**Issue by imbudhiraja** [kevinejohn/react-native-keyevent#4]

**Comment by kevinejohn** [comment]
Could you elaborate? Are you talking about the Android Back button?

**Comment by imbudhiraja** [comment]
yes i'm talking about Android keyboard back button.

Thanks
Manish Budhiraja

**Comment by kevinejohn** [comment]
React Native already has an easy way to read that: https://facebook.github.io/react-native/releases/0.41/docs/backandroid.html

**Comment by imbudhiraja** [comment]
I'm talking about soft keyboard back button not Android Back.

Thanks
Manish Budhiraja

On Feb 23, 2017 9:19 AM, "Kevin Johnson" <notifications@github.com> wrote:

React Native already has an easy way to read that:
https://facebook.github.io/react-native/releases/0.41/docs/backandroid.html

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/kevinejohn/react-native-keyevent/issues/4#issuecomment-281886799>,
or mute the thread

**Comment by nthtran** [comment]
@kevinejohn Hi so is it possible to listen to keyboard backspaces with this library?

**Comment by kevinejohn** [comment]
@nthtran theoretically yes: https://developer.android.com/reference/android/view/KeyEvent.html#KEYCODE_DEL

I haven't personally tried it though so I can't verify it. Let me know if it does work

**Comment by Mactub07** [comment]
@kevinejohn ,  keyboard backspaces is not listening :( . is it possible to implement one? RN-0.42, tested in avd emulator

**Comment by kevinejohn** [comment]
Ah that's unfortunate. I wish I had an answer right now. Any expert android developers out there that know a solution?

**Comment by Mactub07** [comment]
Btw I've create own native module to fire key-events, it works like your module, but not listen backspace events, hope this happens only on emulator

**Comment by kevinejohn** [comment]
@Mactub07 firing key-events would be a great addition to this library. Do you care to open source it or make a pull-request to this library?

**Comment by imbudhiraja** [comment]
Keycode for android keyboard backpress is 67.
