### ISSUE TITLE
Maintenance of this project

### ISSUE THREAD

**Issue by freeboub** [kevinejohn/react-native-keyevent#69]
Hello @Kevinejohn
I saw this project doesn't seems maintained anymore.
Do you agree to transfer ownership to someone else ?
I agree to take the lead if you want.
Thank you

**Comment by kevinejohn** [comment]
Feel free to make pull requests and I'll review and merge updates. No offense but your profile doesn't seem maintained.

**Comment by freeboub** [comment]
,👍
