### ISSUE TITLE
Listener is not removing.

### ISSUE THREAD

**Issue by dhksrini** [kevinejohn/react-native-keyevent#8]
I have a function and calling it onKeyUpListener. I'm removing the listener in componentWillUnmount. 
My code is below:
`componentDidMount(){
  KeyEvent.onKeyUpListener((keyCode) => {
      if(keyCode == '67'){
        this.handleBackSpace();
      }
    });
}`
and 

`componentWillUnmount() {
KeyEvent.removeKeyUpListener();
}`

This causing issue on other screens. Actually, Listener is not removing.

**Comment by kevinejohn** [comment]
I just published a new version `0.0.6` that may fix this issue. Let me know if it doesn't work.
